//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4337
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string Code { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Index { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
        public Nullable<int> Flat { get; set; }
        public string Email { get; set; }
    }
}
